version: 2

jobs:
  build:
    docker:
      - image: streamrail/circle2:latest
        env:
          - DISPLAY=:99
          - CHROME_BIN=/usr/bin/google-chrome
    working_directory: /tincan
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - tincan-npm-deps-{{ .Branch }}-v1
      - run:
          name: NPM Install
          command: |
            npm prune
            npm install
            npm update
      - run:
          name: AWS Install
          command: |
            pip install awscli
      - save_cache:
          key: tincan-npm-deps-{{ .Branch }}-v1
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: |
            npm run build
            xvfb-run npm run test
      - run:
          name: Deploy
          command: |
            npm run deploy